name: Jenkins Unit Testing

on: 
    pull_request:
        branches:
            - master
    push:
        branches:
            - master

concurrency:
    group: unit-test

jobs:
    Jenkins-Unit-Testing:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            - uses: FranzDiebold/github-env-vars-action@v2
            - name: Variables
              run: |
                echo "$CI_HEAD_REF"
            - name: Print
              run: echo ${{ env.CI_ACTION_REF_NAME }}
            - name: Trigger-build
              run: echo ${{ secrets.JENKINS_URL }}
