name: Jenkins Unit Testing

on: 
    pull_request:
        branches:
            - master
    push:
        branches:
            - master

concurrency:
    group: unit-test

jobs:
    Jenkins-Unit-Testing:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            - uses: FranzDiebold/github-env-vars-action@v2
            - name: Variables
              run: |
                echo "$CI_HEAD_REF"
            - name: Print
              run: echo ${{ env.CI_ACTION_REF_NAME }}
            - name: Trigger-build
              uses: SimonMaghiar/jenkins-trigger@main
              with:
                url: ${{ secrets.JENKINS_URL }}
                user_name: ${{ secrets.JENKINS_USER }}
                api_token: ${{ secrets.JENKINS_PAT }}
                job_name: "BMI-Calculator"
                parameter: '{"branch": "${{ env.CI_ACTION_REF_NAME }}", "repo": "${{ env.CI_REPOSITORY_NAME }}", "base": "${{ env.CI_BASE_REF }}"}'
                timeout: "5000"
